module.exports = {
    content: ["./index.html", "./src/**/*.{vue,js,ts,jsx,tsx}"],
    theme: {
        extend: {
            colors: {
                "interactive-01": "var(--pds-interactive-01)",
                "interactive-02": "var(--pds-interactive-02)",
                "interactive-03": "var(--pds-interactive-03)",
                "interactive-04": "var(--pds-interactive-04)",
                "danger-01": "var(--pds-danger-01)",
                "danger-02": "var(--pds-danger-02)",
                "button-separator": "var(--pds-button-separator)",
                "ui-01": "var(--pdsui-01)",
                "ui-02": "var(--pds-ui-02)",
                "ui-03": "var(--pds-ui-03)",
                "ui-04": "var(--pds-ui-04)",
                "ui-05": "var(--pds-ui-05)",
                "decorative-01": "var(--pds-decorative-01)",
                "text-01": "var(--pds-text-01)",
                "text-02": "var(--pds-text-02)",
                "text-03": "var(--pds-text-03)",
                "text-04": "var(--pds-text-04)",
                "text-05": "var(--pds-text-05)",
                "hover-primary": "var(--pds-hover-primary)",
                "hover-primary-text": "var(--pds-hover-primary-text)",
                "hover-secondary": "var(--pds-hover-secondary)",
                "hover-tertiary": "var(--pds-hover-tertiary)",
                "hover-ui": "var(--pds-hover-ui)",
                "inverse-01": "var(--pds-inverse-01)",
                "active-primary": "var(--pds-active-primary)",
            },
        },
        fontFamily: {
            Roboto: ["Roboto, sans-serif"],
        },
        container: {
            padding: "2rem",
            center: true,
        },
        screens: {
            sm: "640px",
            md: "768px",
        },
    },
    plugins: [],
};